apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: static
  name: static
spec:
  output:
    to:
      kind: ImageStreamTag
      name: static:latest
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/weepee-org/openshift-example-project.git
    contextDir: static/
    type: Git
strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: static:latest
    type: Docker
